FROM python:3.11-slim

# instalar ffmpeg completo (inclui ffprobe)
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -U yt-dlp

COPY . .

CMD ["python", "main.py"]
